# Generated by Django 3.2.4 on 2021-07-10 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, choices=[('Tennis', 'Tennis'), ('Chess', 'Chess'), ('Soccer', 'Soccer'), ('Netball', 'Netball'), ('None', 'None')], max_length=100, null=True, verbose_name='sport')),
                ('stream1', models.CharField(blank=True, choices=[('Technical stream 2', 'Technical stream 2'), ('Technical stream 1', 'Technical stream 1'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('None', 'None')], max_length=200, null=True, verbose_name='stream1')),
                ('stream2', models.CharField(blank=True, choices=[('Technical stream 2', 'Technical stream 2'), ('Technical stream 1', 'Technical stream 1'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('None', 'None')], max_length=200, null=True, verbose_name='stream2')),
                ('sub1', models.CharField(choices=[('Information technology', 'Information technology'), ('Electronics', 'Electronics'), ('Physical science', 'Physical science'), ('English', 'English'), ('Maths', 'Maths'), ('Sepedi', 'Sepedi'), ('Life science', 'Life science'), ('Life orientation', 'Life orientation'), ('Accounting', 'Accounting'), ('Business studies', 'Business studies'), ('Technical science', 'Technical science')], max_length=200, verbose_name='sub1')),
                ('sub2', models.CharField(blank=True, choices=[('Information technology', 'Information technology'), ('Electronics', 'Electronics'), ('Physical science', 'Physical science'), ('English', 'English'), ('Maths', 'Maths'), ('Sepedi', 'Sepedi'), ('Life science', 'Life science'), ('Life orientation', 'Life orientation'), ('Accounting', 'Accounting'), ('Business studies', 'Business studies'), ('Technical science', 'Technical science')], max_length=200, verbose_name='sub2')),
                ('sub3', models.CharField(blank=True, choices=[('Information technology', 'Information technology'), ('Electronics', 'Electronics'), ('Physical science', 'Physical science'), ('English', 'English'), ('Maths', 'Maths'), ('Sepedi', 'Sepedi'), ('Life science', 'Life science'), ('Life orientation', 'Life orientation'), ('Accounting', 'Accounting'), ('Business studies', 'Business studies'), ('Technical science', 'Technical science')], max_length=200, null=True, verbose_name='sub3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
