# Generated by Django 3.2.4 on 2021-07-12 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheraccount',
            name='sub1',
            field=models.CharField(choices=[('Information technology', 'Information technology'), ('Electronics', 'Electronics'), ('Physical science', 'Physical science'), ('English', 'English'), ('Maths', 'Maths'), ('Sepedi', 'Sepedi'), ('Life science', 'Life science'), ('Life orientation', 'Life orientation'), ('Accounting', 'Accounting'), ('Business studies', 'Business studies'), ('Technical science', 'Technical science'), ('None', 'None')], max_length=200, verbose_name='sub1'),
        ),
        migrations.AlterField(
            model_name='teacheraccount',
            name='sub2',
            field=models.CharField(blank=True, choices=[('Information technology', 'Information technology'), ('Electronics', 'Electronics'), ('Physical science', 'Physical science'), ('English', 'English'), ('Maths', 'Maths'), ('Sepedi', 'Sepedi'), ('Life science', 'Life science'), ('Life orientation', 'Life orientation'), ('Accounting', 'Accounting'), ('Business studies', 'Business studies'), ('Technical science', 'Technical science'), ('None', 'None')], max_length=200, verbose_name='sub2'),
        ),
        migrations.AlterField(
            model_name='teacheraccount',
            name='sub3',
            field=models.CharField(blank=True, choices=[('Information technology', 'Information technology'), ('Electronics', 'Electronics'), ('Physical science', 'Physical science'), ('English', 'English'), ('Maths', 'Maths'), ('Sepedi', 'Sepedi'), ('Life science', 'Life science'), ('Life orientation', 'Life orientation'), ('Accounting', 'Accounting'), ('Business studies', 'Business studies'), ('Technical science', 'Technical science'), ('None', 'None')], max_length=200, null=True, verbose_name='sub3'),
        ),
        migrations.AlterField(
            model_name='teacheraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
