# Generated by Django 3.2.4 on 2021-07-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210712_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheraccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
