# Generated by Django 3.2.4 on 2021-07-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaccount',
            name='dob',
            field=models.DateField(default='2000-1-1', verbose_name='dob'),
        ),
        migrations.AddField(
            model_name='baseaccount',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='baseaccount',
            name='is_learner',
            field=models.BooleanField(default=True, verbose_name='is_learner'),
        ),
        migrations.AddField(
            model_name='baseaccount',
            name='name',
            field=models.CharField(default='None', max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='baseaccount',
            name='phone_no',
            field=models.IntegerField(default=0, unique=True, verbose_name='phone_no'),
        ),
        migrations.AddField(
            model_name='baseaccount',
            name='surname',
            field=models.CharField(default='None', max_length=255, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='baseaccount',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='username'),
        ),
    ]
