# Generated by Django 3.2.4 on 2021-07-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210712_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseaccount',
            name='dob',
            field=models.DateField(default=1998, verbose_name='dob'),
        ),
    ]
