# Generated by Django 3.2.4 on 2021-07-10 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('intro', models.CharField(max_length=500, verbose_name='intro')),
                ('content', models.CharField(blank=True, max_length=5000, null=True, verbose_name='content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('draft', models.BooleanField(default=True, verbose_name='draft')),
                ('grade', models.BooleanField(default=False, verbose_name='grade')),
                ('stream', models.BooleanField(default=False, verbose_name='stream')),
                ('sport', models.BooleanField(default=False, verbose_name='sport')),
                ('club', models.BooleanField(default=False, verbose_name='club')),
                ('teachers', models.BooleanField(default=False, verbose_name='teachers')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('views', models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
