# Generated by Django 3.2.4 on 2021-07-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210711_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('General', 'General'), ('Announcement', 'Announcement'), ('Notice', 'Notice'), ('Update', 'Update'), ('Important', 'Important')], max_length=100, verbose_name='post_type'),
        ),
    ]
