# Generated by Django 3.2.4 on 2021-07-10 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(blank=True, choices=[('Technical stream 2', 'Technical stream 2'), ('Technical stream 1', 'Technical stream 1'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('None', 'None')], max_length=100, null=True, verbose_name='stream')),
                ('grade', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='grade')),
                ('sport', models.CharField(blank=True, choices=[('Tennis', 'Tennis'), ('Chess', 'Chess'), ('Soccer', 'Soccer'), ('Netball', 'Netball'), ('None', 'None')], max_length=100, null=True, verbose_name='sport')),
                ('club', models.CharField(blank=True, choices=[('Robotics', 'Robotics'), ('Science', 'Science'), ('English society', 'English society'), ('None', 'None')], max_length=100, null=True, verbose_name='club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
