# Generated by Django 3.2.4 on 2021-07-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0003_alter_learneraccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='learneraccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
